### ISSUE TITLE
Private repos

### ISSUE THREAD

**Issue by sj222mk** [NapCat-App/Support#8]
Hi!
I can not find my repos in the app. Under my profile it shows zero repos? (They are private, course I am a student). How can I find them so I can do my homework?

Best regards Sofia

**Comment by zetachang** [comment]
Hi, sorry for the late reply. There are two workaround to solve this issue,

1) Search for the repo
2) If failed to find, star the repo in desktop. And you can find an activity saying you star it in your own "Public Activity". 

Hope this will help, and definitely, these bugs will all be fixed in the next release. :smiley: 

Cheers

David

**Comment by zetachang** [comment]
This issue has been fixed in the latest version (1.3.1). Thanks for the patience and have fun reading code!

Cheers! :beers:
